// PROTOTYPE — ticket #27, the voter home. Generates data.js from two earlier
// prototypes' data, both public TMDB/DTDD payloads:
//   tmp/revdata.js  = prototypes/reveal/data.js on branch prototype/reveal (#29):
//                     32 real candidates, nine voters, notes, everyone's scores,
//                     vetoes, seen-it, Dani's watched list
//   tmp/sugdata.js  = prototypes/suggest-screen/data.js on prototype/suggest-screen
//                     (#21): recorded TMDB searches, and three films not in the 32
// The three extras become the pool's other states: two long films the admin
// drops in APPROVE, and one late suggestion that lands mid-VOTE (#15).
// Run: node prototypes/voter-home/gen-data.mjs
import { readFileSync, writeFileSync } from "node:fs";
const grab = (p, v) => { const s = readFileSync(p, "utf8"); const w = {}; new Function("window", s)(w); return w[v]; };
const R = grab("tmp/revdata.js", "DATA"), S = grab("tmp/sugdata.js", "PROTO");
const extra = [
  [120, "Gergő", "Extended edition or nothing. Yes it's 228 minutes. Yes I'm serious.", "APPROVE", "dropped"],
  [438631, "Bence", "Big screen, big sound, 155 minutes of sand. Not horror, but a marathon is a marathon.", "APPROVE", "dropped"],
  [9877, "Iván", "Late one, sorry — 90s slasher, campus legends, Jared Leto. Perfect 1 a.m. filler.", "VOTE", "pending"],
];
const films = R.films.map((f, i) => ({ ...f, when: "SUGGEST", fate: "approved", order: i }));
for (const [id, by, pitch, when, fate] of extra) {
  const f = S.films[id];
  films.push({ id, title: f.title, year: f.year, runtime: id === 120 ? 228 : f.runtime, runtimeSrc: id === 120 ? "edited" : "TMDB", tmdbRuntime: f.runtime,
    cert: f.cert, poster: f.poster_path, director: f.director, trailer: f.trailer, imdb: f.imdb_id, suggester: by, notes: { [by]: pitch },
    dtdd: f.dtdd, when, fate, order: films.length });
}
// the searches drive the working picker in the Suggest panel
writeFileSync("prototypes/voter-home/data.js", "// generated by gen-data.mjs — PROTOTYPE #27\nwindow.DATA = " +
  JSON.stringify({ me: R.me, voters: R.voters, films, scores: R.scores, seen: R.seen, vetoes: R.vetoes, watched: R.watched, searches: S.searches, searchFilms: S.films }) + ";\n");
console.log(films.length, "films");
