// PROTOTYPE — ticket #24. Generates data.js: 32 real candidates (title, year,
// runtime, genres from the group's own past suggestions, see #19) and a
// deterministic, *correlated* vote matrix for nine voters. Correlated on purpose:
// #17 warned that independent draws manufacture a plateau. Run: node gen-data.mjs
import { readFileSync, writeFileSync } from "node:fs";

const raw = JSON.parse(readFileSync(new URL("../../../results.json", import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1")));
const pick = [
  "Evil Dead","The Wolf House","Infested / Vermines","Weapons","Bring Her Back","Triangle",
  "Final Destination Bloodlines","28 Days Later","PG: Psycho Goreman","Willy's Wonderland","Time Lapse",
  "Nightbreed (directors cut)","Winnie-the-Pooh: Blood and Honey 2","ThanksKilling","The Blob","Goodnight Mommy",
  "Slaxx","Arachnophobia","Death Becomes Her","Longlegs","Late Night with the Devil","Terrifier","The Shining",
  "When Evil Lurks","In a Violent Nature","The Thing","The Exorcist","Coco","Phil Tippet's Mad God","Cube",
  "Werewolf by Night","Midsommar",
];
// affinity: [gore, comedy, prestige] in -1..1
const aff = {
  "Evil Dead":[1,0,0],"The Wolf House":[0,-0.5,1],"Infested / Vermines":[0.6,0,0.2],"Weapons":[0.3,0,0.8],
  "Bring Her Back":[0.6,-0.3,0.7],"Triangle":[0,0,0.6],"Final Destination Bloodlines":[0.8,0.4,-0.3],
  "28 Days Later":[0.5,0,0.5],"PG: Psycho Goreman":[0.4,1,-0.3],"Willy's Wonderland":[0.3,0.9,-0.6],
  "Time Lapse":[-0.3,0,0.3],"Nightbreed (directors cut)":[0.4,0.2,0.4],"Winnie-the-Pooh: Blood and Honey 2":[0.6,0.6,-1],
  "ThanksKilling":[0.2,1,-1],"The Blob":[0.6,0.4,0.1],"Goodnight Mommy":[0.1,-0.5,0.9],"Slaxx":[0.3,1,-0.5],
  "Arachnophobia":[0,0.7,0.2],"Death Becomes Her":[-0.3,0.9,0.3],"Longlegs":[0.2,-0.4,0.8],
  "Late Night with the Devil":[0.2,0.2,0.7],"Terrifier":[1,0.1,-0.8],"The Shining":[0,-0.2,1],
  "When Evil Lurks":[0.9,-0.3,0.5],"In a Violent Nature":[0.9,-0.2,0.2],"The Thing":[0.6,0,0.9],
  "The Exorcist":[0.2,-0.4,1],"Coco":[-1,0.4,0.3],"Phil Tippet's Mad God":[0.5,-0.5,0.7],"Cube":[0.3,0.1,0.4],
  "Werewolf by Night":[0,0.6,0.3],"Midsommar":[0.2,-0.5,1],
};
const seen = new Set();
const films = [];
for (const x of raw) {
  if (!x.id || seen.has(x.id) || !pick.includes(x.title)) continue;
  seen.add(x.id);
  films.push({ id: x.id, title: x.title, year: x.year || null, runtime: x.runtime, cert: x.cert || "", genres: x.genres || [] });
}
films.sort((a, b) => pick.indexOf(a.title) - pick.indexOf(b.title));

// voters and their faction weights [gore, comedy, prestige]
const voters = [
  ["Ana",    [ 0.1, 1.0, 0.2]],
  ["Bence",  [ 1.0, 0.2,-0.2]],
  ["Csilla", [-0.2, 0.9, 0.4]],
  ["Dani",   [ 0.0,-0.2, 1.0]],
  ["Eszter", [-0.6, 0.1, 1.0]],
  ["Feri",   [ 0.9, 0.5,-0.1]],
  ["Gergő",  [ 0.8,-0.1, 0.5]],
  ["Hanna",  [ 0.2, 0.8, 0.1]],
  ["Iván",   [ 0.5, 0.5, 0.5]], // has not voted yet — the "8 of 9" floor-set line
];
let s = 20260917; const rnd = () => (s = (s * 1103515245 + 12345) & 0x7fffffff) / 0x7fffffff;
const scores = {}; // scores[voter][filmId] = -1..3 ; absent = not scored
for (const [name, w] of voters) {
  scores[name] = {};
  if (name === "Iván") continue;
  for (const f of films) {
    if (rnd() < 0.08) continue; // left blank
    const a = aff[f.title];
    const v = -0.3 + 2.6 * (a[0]*w[0] + a[1]*w[1] + a[2]*w[2]) + (rnd() - 0.5) * 2.0;
    scores[name][f.id] = Math.max(-1, Math.min(3, Math.round(v)));
  }
}
const byTitle = t => films.find(f => f.title === t).id;
const vetoes = {
  Eszter: [byTitle("Terrifier"), byTitle("In a Violent Nature")],
  Csilla: [byTitle("The Exorcist")],
  Dani:   [byTitle("Winnie-the-Pooh: Blood and Honey 2")],
  Bence:  [byTitle("Coco")],
  Ana:    [byTitle("Terrifier")],
};
const seenIt = {
  Bence: [byTitle("The Thing"), byTitle("The Shining"), byTitle("Evil Dead")],
  Dani:  [byTitle("Midsommar"), byTitle("The Exorcist"), byTitle("The Shining")],
  Hanna: [byTitle("Evil Dead"), byTitle("Coco")],
  Gergő: [byTitle("The Thing")],
  Feri:  [byTitle("Evil Dead"), byTitle("Terrifier")],
};
// a veto overrides a hand score; seen-it keeps the score (it bars representation only, #10)
for (const [v, ids] of Object.entries(vetoes)) for (const id of ids) delete scores[v][id];

const out = { films, voters: voters.map(v => v[0]), scores, vetoes, seenIt };
writeFileSync(new URL("./data.js", import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1"), "// generated by gen-data.mjs — PROTOTYPE #24\nwindow.DATA = " + JSON.stringify(out) + ";\n");
console.log(films.length, "films;", Object.values(scores).map(o => Object.keys(o).length).join(","), "scores per voter");
