// PROTOTYPE #22 — slims the voter-home prototype's data (real TMDB films, generated votes) to what the timetable needs.
// Run from the repo root:  node prototypes/timetable-editor/gen-data.mjs
import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
const src = execSync("git show prototype/voter-home:prototypes/voter-home/data.js", { maxBuffer: 1 << 26 }).toString();
const window = {}; eval(src);
const D = window.DATA;
const out = {
  voters: D.voters,
  films: D.films.map(f => ({ id: f.id, title: f.title, year: f.year, runtime: f.runtime, poster: f.poster, trailer: f.trailer || null, director: f.director })),
  vetoes: D.vetoes,
};
writeFileSync(new URL("./data.js", import.meta.url), "// generated by gen-data.mjs — PROTOTYPE #22\nwindow.DATA = " + JSON.stringify(out) + ";\n");
console.log("films", out.films.length, "voters", out.voters.length);
