// PROTOTYPE — ticket #28, the admin console. Generates data.js from the #27
// prototype's data (public TMDB/DTDD payloads, the group's own past suggestions):
//   tmp/vhdata.js = prototypes/voter-home/data.js on branch prototype/voter-home
//   (git show prototype/voter-home:prototypes/voter-home/data.js > tmp/vhdata.js)
// Drops the recorded searches (the admin never suggests) and adds the one thing the
// approve screen needs that #27 did not: every film's TMDB runtime, so the
// "differs from TMDB" flag has something to compare against. Nightbreed gets the
// group's own director's-cut edit (#19), next to #27's 228-minute Fellowship.
// Run: node prototypes/admin-console/gen-data.mjs
import { readFileSync, writeFileSync } from "node:fs";
const w = {}; new Function("window", readFileSync("tmp/vhdata.js", "utf8"))(w);
const D = w.DATA;
const films = D.films.map(f => ({ ...f, tmdbRuntime: f.tmdbRuntime ?? f.runtime }));
const nb = films.find(f => f.id === 20481); nb.tmdbRuntime = 102; nb.runtimeSrc = "edited";
writeFileSync("prototypes/admin-console/data.js", "// generated by gen-data.mjs — PROTOTYPE #28\nwindow.DATA = " +
  JSON.stringify({ voters: D.voters, films, scores: D.scores, vetoes: D.vetoes }) + ";\n");
console.log(films.length, "films");
