// PROTOTYPE — ticket #29, the reveal. Generates data.js from the #9 ballot
// prototype's data (tmp/vote-data.js = prototypes/voting-interface/data.js on
// branch prototype/voting-interface): the same 32 real candidates, the same nine
// voters, notes, DTDD topics and live vetoes. What this adds is EVERYONE'S ballot
// — the thing the reveal shows and the ballot hid.
//
// Scores are deterministic and CORRELATED (three taste factions), as #24 warned
// independent draws manufacture a plateau. Iván never voted (#24's "floor over
// 8 of 9"); Hanna scored ~three quarters of the ballot and left the rest blank
// (#10: blank counts 0 to the solver, but the reveal must not call it "don't
// mind"). "You" are Dani, whose ballot is the #9 prototype's "all scored" state.
//
// Run: node prototypes/reveal/gen-data.mjs     (needs tmp/vote-data.js)
import { readFileSync, writeFileSync } from "node:fs";
const src = readFileSync("tmp/vote-data.js", "utf8");
const V = JSON.parse(src.slice(src.indexOf("{"), src.lastIndexOf("}") + 1));
const ME = V.me;                                    // Dani
const voters = V.voters;                            // Ana … Iván (roster order)
let s = 20260929; const rnd = () => (s = (s * 1103515245 + 12345) & 0x7fffffff) / 0x7fffffff;

// three taste factions: gore, slow-burn dread, camp/fun
const faction = { Ana: [0.3, 0.1, 0.9], Bence: [0.9, 0.3, 0.2], Csilla: [0.2, 0.9, 0.4], Dani: [0.5, 0.7, 0.3], Eszter: [0.1, 0.9, 0.2], Feri: [0.9, 0.2, 0.6], Gergő: [0.7, 0.6, 0.3], Hanna: [0.3, 0.3, 0.9], Iván: [0.5, 0.5, 0.5] };
const appeal = {};                                   // per film: how much of each faction it feeds
for (const f of V.films) appeal[f.id] = [rnd(), rnd(), rnd()].map(x => x * 2 - 1);

const byTitle = t => V.films.find(f => f.title === t).id;
const scores = {}, seen = {}, vetoes = {};
for (const v of voters) { scores[v] = {}; seen[v] = {}; vetoes[v] = {}; }

// vetoes: the ballot prototype's live ones, plus Dani's own
for (const [v, m] of Object.entries(V.vetoes)) for (const [id, r] of Object.entries(m)) vetoes[v][id] = r;
vetoes[ME][byTitle("Winnie-the-Pooh: Blood and Honey 2")] = "we lost an hour to the first one";
vetoes.Gergő[byTitle("Coco")] = "";

// seen-its: a few per voter, Dani's from the ballot prototype
for (const [id] of Object.entries(V.ballots.full.seen)) seen[ME][id] = true;
const seenList = { Ana: ["The Thing", "The Shining", "Arachnophobia", "Death Becomes Her"], Bence: ["The Thing", "28 Days Later", "The Blob", "Evil Dead"], Csilla: ["Midsommar", "Triangle", "Coco"], Eszter: ["The Wolf House", "Goodnight Mommy", "The Shining"], Feri: ["Terrifier", "Final Destination Bloodlines"], Gergő: ["The Exorcist", "Nightbreed (directors cut)"], Hanna: ["Coco", "Willy's Wonderland"] };
for (const [v, ts] of Object.entries(seenList)) for (const t of ts) seen[v][byTitle(t)] = true;

// scores
const hannaSkip = new Set(["Cube", "Time Lapse", "Nightbreed (directors cut)", "ThanksKilling", "Slaxx", "Werewolf by Night", "Phil Tippet's Mad God", "In a Violent Nature"].map(byTitle));
for (const v of voters) {
  if (v === "Iván") continue;                                     // never voted
  for (const f of V.films) {
    if (vetoes[v][f.id] !== undefined) continue;                  // a veto replaces the score (#10)
    if (v === "Hanna" && hannaSkip.has(f.id)) continue;           // left blank
    if (v === ME) { const x = V.ballots.full.scores[f.id]; if (x !== undefined) scores[v][f.id] = x; continue; }
    const w = faction[v], a = appeal[f.id];
    const raw = 1.4 * (w[0] * a[0] + w[1] * a[1] + w[2] * a[2]) + (rnd() - 0.5) * 1.6 + 0.6;
    scores[v][f.id] = Math.max(-1, Math.min(3, Math.round(raw)));
  }
}
// a couple of hand-set cells so the notes and the numbers agree
const set = (v, t, x) => { if (vetoes[v][byTitle(t)] === undefined) scores[v][byTitle(t)] = x; };
set("Hanna", "The Thing", 2); set("Ana", "The Thing", 3); set("Bence", "Midsommar", -1); set("Csilla", "Weapons", 3);
set("Csilla", "Midsommar", 3); set("Eszter", "Midsommar", 3); set("Gergő", "The Exorcist", 3); set("Feri", "Terrifier", 3);
set("Hanna", "Coco", 3); set("Ana", "Coco", 2); set("Csilla", "Coco", 2); set("Feri", "Winnie-the-Pooh: Blood and Honey 2", 1);
set("Bence", "Winnie-the-Pooh: Blood and Honey 2", -1); set("Ana", "Winnie-the-Pooh: Blood and Honey 2", -1);

const out = { me: ME, voters, films: V.films, scores, seen, vetoes, watched: V.watched };
writeFileSync(new URL("./data.js", import.meta.url), "// generated by gen-data.mjs — PROTOTYPE #29\nwindow.DATA = " + JSON.stringify(out) + ";\n");
const n = v => Object.keys(scores[v]).length + Object.keys(vetoes[v]).length;
console.log(V.films.length, "films;", voters.map(v => `${v} ${n(v)}`).join(", "));
