# PROTOTYPE — ticket #23. Builds data.js from the live DTDD vocabulary (tmp/dtdd_*.json,
# fetched from /api/v3/topics, /topiccategories, /topicsupercategories) and the #29
# prototype's 32-film pool. Run from the repo root:  python prototypes/trigger-list/gen-data.py
import json
R = lambda p: json.load(open(p, encoding="utf-8"))
T, C, S = R("tmp/dtdd_topics.json"), R("tmp/dtdd_topiccategories.json"), R("tmp/dtdd_topicsupercategories.json")
raw = open("tmp/reveal-data.js", encoding="utf-8").read()
pool = json.loads(raw[raw.index("{"):].rstrip().rstrip(";"))["films"]
cat_sup = {c["id"]: c["topicSuperCategoryId"] for c in C}
by_does = {t["doesName"]: t["id"] for t in T}
films, carriers = [], {t["id"]: [] for t in T}
for i, f in enumerate(pool):
    films.append({"title": f["title"], "year": f["year"]})
    for x in (f.get("dtdd") or {}).get("topics", []):
        if x["yes"] >= 5 and x["yes"] > x["no"] and x["topic"] in by_does:   # #20's rule
            carriers[by_does[x["topic"]]].append((x["yes"], i))
topics = [{"id": t["id"], "name": t["minimalName"], "desc": (t["description"] or "").strip(),
           "kw": t["keywords"] or "", "sup": cat_sup[t["topicCategoryId"]],
           "films": [i for _, i in sorted(carriers[t["id"]], reverse=True)]}   # strongest claim first
          for t in sorted(T, key=lambda t: t["minimalName"].lower())]
supers = [{"id": s["id"], "name": s["name"]} for s in sorted(S, key=lambda s: s["name"])]
out = {"supers": supers, "topics": topics, "films": films}
open("prototypes/trigger-list/data.js", "w", encoding="utf-8").write(
    "// generated by gen-data.py — PROTOTYPE #23\nwindow.DATA = " + json.dumps(out, ensure_ascii=False) + ";\n")
print(len(topics), "topics,", len(supers), "sections,", len(films), "films")
